### ISSUE TITLE
Inconsistencies in NavBar

### ISSUE THREAD

**Issue by edisonlimllk** [edisonlimllk/QuotesApp#11]
The NavBars in the About Us page and Browse Quotes page do not reflect our existing functionalities. Either we can develop the features in the NavBar or remove those items from the NavBar. 

![image](https://user-images.githubusercontent.com/115971906/205612607-e89dd96e-ca27-4cb2-8a0b-1b3f3896108b.png)

However, I think since we are a quotes app that features, pricing, FAQs and a search bar do not seem relevant to the app. I think we should remove those from the navbar. I can do it.

@XavierHoPeiYi @meepanish Since they are your pages what do you think?

**Comment by XavierHoPeiYi** [comment]
I think we should remove the items in the NavBar

**Comment by edisonlimllk** [comment]
> I think we should remove the items in the NavBar

Okay, I will go ahead to make the bugfix branch and handle it.

**Comment by edisonlimllk** [comment]
I have made the bug fix branch, debugged the issue and made a pull request. Xavier reviewed my pull request and merged the bug-fix branch with the development branch. The issue is resolved.
